package cr.ac.una.prograiv.project.domain;
// Generated 03/10/2017 05:48:10 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asignacion generated by hbm2java
 */
@Entity
@Table(name="asignacion"
    ,catalog="transporte"
)
public class Asignacion  implements java.io.Serializable {

     private Integer id;
     private Integer chofer;
     private Integer vehiculo;

    public Asignacion() {
    }

    public Asignacion(Integer id, Integer chofer, Integer vehiculo) {
       this.id = id;
       this.chofer = chofer;
       this.vehiculo = vehiculo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pkIdChofer", column=@Column(name="PK_idChofer", nullable=false) ), 
        @AttributeOverride(name="pkIdVehiculo", column=@Column(name="PK_idVehiculo", nullable=false) ) } )
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_idChofer", nullable=false, insertable=false, updatable=false)
    public Integer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Integer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_idVehiculo", nullable=false, insertable=false, updatable=false)
    public Integer getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Integer vehiculo) {
        this.vehiculo = vehiculo;
    }




}


