package cr.ac.una.prograiv.project.domain;
// Generated 04/10/2017 01:05:04 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asignacion generated by hbm2java
 */
@Entity
@Table(name="asignacion"
    ,catalog="transporte"
)
public class Asignacion  implements java.io.Serializable {


     private Integer pkIdAsignacion;
     private Chofer chofer;
     private Vehiculo vehiculo;

    public Asignacion() {
    }

    public Asignacion(Chofer chofer, Vehiculo vehiculo) {
       this.chofer = chofer;
       this.vehiculo = vehiculo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_idAsignacion", unique=true, nullable=false)
    public Integer getPkIdAsignacion() {
        return this.pkIdAsignacion;
    }
    
    public void setPkIdAsignacion(Integer pkIdAsignacion) {
        this.pkIdAsignacion = pkIdAsignacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_idChofer", nullable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PK_idVehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }




}


