package cr.ac.una.prograiv.project.domain;
// Generated 03/10/2017 05:48:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsignacionId generated by hbm2java
 */
@Embeddable
public class AsignacionId  implements java.io.Serializable {


     private int pkIdChofer;
     private int pkIdVehiculo;

    public AsignacionId() {
    }

    public AsignacionId(int pkIdChofer, int pkIdVehiculo) {
       this.pkIdChofer = pkIdChofer;
       this.pkIdVehiculo = pkIdVehiculo;
    }
   


    @Column(name="PK_idChofer", nullable=false)
    public int getPkIdChofer() {
        return this.pkIdChofer;
    }
    
    public void setPkIdChofer(int pkIdChofer) {
        this.pkIdChofer = pkIdChofer;
    }


    @Column(name="PK_idVehiculo", nullable=false)
    public int getPkIdVehiculo() {
        return this.pkIdVehiculo;
    }
    
    public void setPkIdVehiculo(int pkIdVehiculo) {
        this.pkIdVehiculo = pkIdVehiculo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsignacionId) ) return false;
		 AsignacionId castOther = ( AsignacionId ) other; 
         
		 return (this.getPkIdChofer()==castOther.getPkIdChofer())
 && (this.getPkIdVehiculo()==castOther.getPkIdVehiculo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPkIdChofer();
         result = 37 * result + this.getPkIdVehiculo();
         return result;
   }   


}


