package cr.ac.una.prograiv.project.domain;
// Generated 05/10/2017 12:43:10 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chofer generated by hbm2java
 */
@Entity
@Table(name = "chofer",
         catalog = "transporte"
)
public class Chofer implements java.io.Serializable {

    private Integer pkIdChofer;
    private String cedula;
    private String nombre;
    private Date fechaNacimiento;
    private String tipoLicencia;
    private Date vencimientoLicencia;
    private Date ultimaFecha;
    private String ultimoUsuario;

    public Chofer() {
    }

    public Chofer(String cedula, String nombre, Date fechaNacimiento, String tipoLicencia, Date vencimientoLicencia, Date ultimaFecha, String ultimoUsuario) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.tipoLicencia = tipoLicencia;
        this.vencimientoLicencia = vencimientoLicencia;
        this.ultimaFecha = ultimaFecha;
        this.ultimoUsuario = ultimoUsuario;
    }

    public Chofer(Integer pkIdChofer, String cedula, String nombre, Date fechaNacimiento, String tipoLicencia, Date vencimientoLicencia, Date ultimaFecha, String ultimoUsuario) {
        this.pkIdChofer = pkIdChofer;
        this.cedula = cedula;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.tipoLicencia = tipoLicencia;
        this.vencimientoLicencia = vencimientoLicencia;
        this.ultimaFecha = ultimaFecha;
        this.ultimoUsuario = ultimoUsuario;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "PK_idChofer", unique = true, nullable = false)
    public Integer getPkIdChofer() {
        return this.pkIdChofer;
    }

    public void setPkIdChofer(Integer pkIdChofer) {
        this.pkIdChofer = pkIdChofer;
    }

    @Column(name = "cedula", nullable = false, length = 15)
    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaNacimiento", nullable = false, length = 10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Column(name = "tipoLicencia", nullable = false, length = 45)
    public String getTipoLicencia() {
        return this.tipoLicencia;
    }

    public void setTipoLicencia(String tipoLicencia) {
        this.tipoLicencia = tipoLicencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "vencimientoLicencia", nullable = false, length = 10)
    public Date getVencimientoLicencia() {
        return this.vencimientoLicencia;
    }

    public void setVencimientoLicencia(Date vencimientoLicencia) {
        this.vencimientoLicencia = vencimientoLicencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ultimaFecha", nullable = false, length = 10)
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }

    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }

    @Column(name = "ultimoUsuario", nullable = false, length = 45)
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }

    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
}
