package cr.ac.una.prograiv.project.domain;
// Generated 04/10/2017 01:05:04 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historial generated by hbm2java
 */
@Entity
@Table(name="historial"
    ,catalog="transporte"
)
public class Historial  implements java.io.Serializable {


     private Integer pkIdHistorial;
     private Chofer chofer;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private Serializable origen;
     private Serializable destino;
     private double monto;
     private int tiempo;
     private String retroalimentacion;
     private Date ultimaFecha;
     private String ultimoUsuario;

    public Historial() {
    }

    public Historial(Chofer chofer, Usuario usuario, Vehiculo vehiculo, Serializable origen, Serializable destino, double monto, int tiempo, String retroalimentacion, Date ultimaFecha, String ultimoUsuario) {
       this.chofer = chofer;
       this.usuario = usuario;
       this.vehiculo = vehiculo;
       this.origen = origen;
       this.destino = destino;
       this.monto = monto;
       this.tiempo = tiempo;
       this.retroalimentacion = retroalimentacion;
       this.ultimaFecha = ultimaFecha;
       this.ultimoUsuario = ultimoUsuario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_idHistorial", unique=true, nullable=false)
    public Integer getPkIdHistorial() {
        return this.pkIdHistorial;
    }
    
    public void setPkIdHistorial(Integer pkIdHistorial) {
        this.pkIdHistorial = pkIdHistorial;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_idChofer", nullable=false)
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_idVehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="origen", nullable=false)
    public Serializable getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(Serializable origen) {
        this.origen = origen;
    }

    
    @Column(name="destino", nullable=false)
    public Serializable getDestino() {
        return this.destino;
    }
    
    public void setDestino(Serializable destino) {
        this.destino = destino;
    }

    
    @Column(name="monto", nullable=false, precision=22, scale=0)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="tiempo", nullable=false)
    public int getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(int tiempo) {
        this.tiempo = tiempo;
    }

    
    @Column(name="retroalimentacion", nullable=false, length=200)
    public String getRetroalimentacion() {
        return this.retroalimentacion;
    }
    
    public void setRetroalimentacion(String retroalimentacion) {
        this.retroalimentacion = retroalimentacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ultimaFecha", nullable=false, length=10)
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }

    
    @Column(name="ultimoUsuario", nullable=false, length=45)
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }




}


