package cr.ac.una.prograiv.project.domain;
// Generated 03/10/2017 05:48:10 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,catalog="transporte"
)
public class Vehiculo  implements java.io.Serializable {


     private Integer pkIdVehiculo;
     private Integer usuario;
     private int ano;
     private String modelo;
     private String placa;
     private String color;
     private Serializable ubicacion;
     private boolean activo;
     private boolean espera;
     private Date ultimaFecha;
     private String ultimoUsuario;
     private Set<Asignacion> asignacions = new HashSet<Asignacion>(0);
     private Set<Historial> historials = new HashSet<Historial>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(Integer usuario, int ano, String modelo, String placa, String color, Serializable ubicacion, boolean activo, boolean espera, Date ultimaFecha, String ultimoUsuario) {
        this.usuario = usuario;
        this.ano = ano;
        this.modelo = modelo;
        this.placa = placa;
        this.color = color;
        this.ubicacion = ubicacion;
        this.activo = activo;
        this.espera = espera;
        this.ultimaFecha = ultimaFecha;
        this.ultimoUsuario = ultimoUsuario;
    }
    public Vehiculo(Integer usuario, int ano, String modelo, String placa, String color, Serializable ubicacion, boolean activo, boolean espera, Date ultimaFecha, String ultimoUsuario, Set<Asignacion> asignacions, Set<Historial> historials) {
       this.usuario = usuario;
       this.ano = ano;
       this.modelo = modelo;
       this.placa = placa;
       this.color = color;
       this.ubicacion = ubicacion;
       this.activo = activo;
       this.espera = espera;
       this.ultimaFecha = ultimaFecha;
       this.ultimoUsuario = ultimoUsuario;
       this.asignacions = asignacions;
       this.historials = historials;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK_idVehiculo", unique=true, nullable=false)
    public Integer getPkIdVehiculo() {
        return this.pkIdVehiculo;
    }
    
    public void setPkIdVehiculo(Integer pkIdVehiculo) {
        this.pkIdVehiculo = pkIdVehiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_idUsuario", nullable=false)
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="ano", nullable=false)
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }

    
    @Column(name="modelo", nullable=false, length=45)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="placa", nullable=false, length=45)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    
    @Column(name="color", nullable=false, length=45)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="ubicacion", nullable=false)
    public Serializable getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Serializable ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    
    @Column(name="espera", nullable=false)
    public boolean isEspera() {
        return this.espera;
    }
    
    public void setEspera(boolean espera) {
        this.espera = espera;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ultimaFecha", nullable=false, length=10)
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }

    
    @Column(name="ultimoUsuario", nullable=false, length=45)
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set<Asignacion> getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set<Asignacion> asignacions) {
        this.asignacions = asignacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set<Historial> getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set<Historial> historials) {
        this.historials = historials;
    }




}


